---

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags: python

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags: python

- name: Install python PyEnv
  git:
    repo: "{{ _python_pyenv_repo }}"
    dest: "{{ python_pyenv_path }}"
    update: "{{python_pyenv_update_git_install}}"
  become_user: "{{python_pyenv_owner}}"
  tags: python

- name: Install python PyEnv-virtualenv plugin
  git:
    repo: "{{_python_pyenv_virtualenv_repo}}"
    dest: "{{ python_pyenv_path }}/plugins/pyenv-virtualenv"
    update: "{{python_pyenv_update_git_install}}"
  become_user: "{{python_pyenv_owner}}"